version: '3.8'

services:
  fitness-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # You'll need to set these environment variables
      # Either in a .env file or pass them directly
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env  # Load from .env file if it exists
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount the fakeData directory for development (optional)
      - ./fakeData:/app/fakeData:ro 